app1/urls.py
from django.urls import path
from .views import matkul_list, matkul_create, home

urlpatterns = [
    path('', home, name='schedule'),
    path('matkul-list/', matkul_list, name='list-matkul'),
    path('create-matkul/', matkul_create, name='create-matkul'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
]

midtermprojectPBP_F03/urls.py
from os import stat
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('to-do-list/', include('to_do_list.urls')),
    path('info-pendidikan/', include('info_pendidikan.urls')),
    path('EventApp/', include('app7_EventApp.urls')),
    path('covid-data/', include('covid_data.urls')),
    path('add-forum/', include('forum.urls')),
    path('susun-jadwal-matkul/', include('app1.urls')),
    path('quiz-of-pandemic/', include('quizes.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import (
    QuizViewList,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
)

app_name = 'quizes'

urlpatterns = [
    path('', QuizViewList.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
]

main/models.py
from django.db import models

# Create your models here.

quizes/models.py
from django.db import models
import random

# Create your models here.
DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="Durasi Waktu Pengerjaan Kuis dalam Menit")
    required_score_to_pass = models.IntegerField(help_text="Skor yang dibutuhkan dalam %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self) :
        return f"{self.name}-{self.topic}"
    
    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]
    
    class Meta:
        verbose_name_plural = 'Quizes'

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

main/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout


def home(request):
    return render(request, 'main/home.html')

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:home")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="main/register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:home")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="main/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("main:home")

quizes/views.py
from typing import Text
from django.db import reset_queries
from django.http.response import JsonResponse
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from questions.models import Question, Answer
from result.models import Result


# Create your views here.
class QuizViewList(ListView):
    model = Quiz
    template_name = 'quizes/main.html'

def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answer():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def save_quiz_view(request, pk):
    print(request.POST)
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        
        data_.pop('csrfmiddlewaretoken')
        
        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        result = []
        correct_ans = None

        for q in questions:
            a_selected = request.POST.get(q.text)
            
            if a_selected !="":
                question_answer = Answer.objects.filter(question=q)
                for a in question_answer:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_ans = a.text
                    else:
                        if a.correct:
                            correct_ans = a.text
                result.append({str(q): {'Jawaban_benar': correct_ans, 'Terjawab': a_selected}})
            else:
                result.append({str(q): 'Belum dijawab'})
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'Lolos': True, 'Skor': score_, 'Hasil': result})
        else:
            return JsonResponse({'Lolos': False, 'Skor': score_, 'Hasil': result})

    

quizes/templates/quizes/main.html
{% extends "main.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'quizes/main.js' %}" defer></script>

{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}  
  <!-- Modal -->
  <div class="modal fade" id="QuizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Mulai Kuis?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-body-confirm"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Tidak</button>
          <button type="button" id="start-button" class="btn btn-success">Ya</button>
        </div>
      </div>
    </div>
  </div>
<div class="h1">Daftar Quiz</div>
<hr>
{% for obj in object_list %}
    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-difficulty="{{obj.difficulty}}"
        data-time="{{obj.time}}"
        data-pass="{{obj.required_score_to_pass}}"
        data-toggle="modal"
        data-target="#QuizStartModal">
        {{obj.name}}
    </button><br>
{% endfor %}
{% endblock content %}

quizes/templates/quizes/quiz.html
{% extends "main.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>Skor untuk Lolos: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box">Timer</div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">Kembali</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}